apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: jolokia-api-server-selfsigned-root-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jolokia-api-server-selfsigned-ca-cert
  namespace: openshift-operators
spec:
  isCA: true
  commonName: jolokia-api-server-selfsigned-ca-cert
  secretName: jolokia-api-server-selfsigned-ca-cert-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - issuer.mydomain.tld
  issuerRef:
    name: jolokia-api-server-selfsigned-root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: jolokia-api-server-selfsigned-issuer
spec:
  ca:
    secretName: jolokia-api-server-selfsigned-ca-cert-secret
