apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: activemq-artemis-jolokia-api-server
  name: activemq-artemis-jolokia-api-server
  labels:
    app: activemq-artemis-jolokia-api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq-artemis-jolokia-api-server
  template:
    metadata:
      labels:
        app: activemq-artemis-jolokia-api-server
    spec:
      containers:
        - name: activemq-artemis-jolokia-api-server
          image: registry.redhat.io/amq-broker-8/amq-broker-80-jolokia-api-server-rhel9@sha256:9b6206a25006c22f59819f9f7db6a261cd0ca85677b9cb1812fc4530a7451418
          env:
            - name: NODE_EXTRA_CA_CERTS
              value: '/var/jolokia-api-server-selfsigned-ca-cert-secret/ca.crt'
          ports:
            - containerPort: 9443
              protocol: TCP
          args: ['dist/app.js']
          command:
            - node
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
          volumeMounts:
            - name: plugin-serving-cert
              readOnly: true
              mountPath: /var/serving-cert
            - name: jolokia-api-server-selfsigned-ca-cert-secret
              readOnly: true
              mountPath: /var/jolokia-api-server-selfsigned-ca-cert-secret
      volumes:
        - name: plugin-serving-cert
          secret:
            secretName: plugin-serving-cert
            defaultMode: 420
        - name: jolokia-api-server-selfsigned-ca-cert-secret
          secret:
            secretName: jolokia-api-server-selfsigned-ca-cert-secret
            defaultMode: 420
      restartPolicy: Always
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
